version: '3'

services:
  frontend:
    image: nginx:1.21.1-alpine
    ports:
      - 8080:80
    volumes:
      - ${PWD}/nginx/html:/usr/share/nginx/html
      - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
  api:
    build: ./fastapi/
    environment:
      PORT: 8000
    volumes:
      - ${PWD}/fastapi:/app
    depends_on:
      - db
  db:
    image: mysql:5.7.35
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ${PWD}/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
